---
# Directory path where specific versions of K3s will be downloaded.
k3s_download_local_dir: "{{ (k3s_cache_local_dir, 'download') | ansible.builtin.path_join }}"

# Directory path where specific versions of K3s binary will be downloaded.
k3s_download_binary_local_dir: "{{ (k3s_download_local_dir, 'binary') | ansible.builtin.path_join }}"

# Path to the K3s binary for the current architecture.
k3s_download_binary_local_file: "{{ (k3s_download_binary_local_dir, 'current', ansible_facts.architecture) | ansible.builtin.path_join }}"

# Path to the K3s install script.
k3s_download_script_local_file: "{{ (k3s_download_script_local_dir, 'current', ansible_facts.architecture) | ansible.builtin.path_join }}"

# Directory path where specific versions of K3s install script will be downloaded.
k3s_download_script_local_dir: "{{ (k3s_download_local_dir, 'script') | ansible.builtin.path_join }}"
