---
galaxy_info:
  author: Kasefuchs
  description: >
    Install and configure K3s Kubernetes distribution,
    including server and agent modes with download,
    installation and configuration management.

  license: MIT
  galaxy_tags:
    - kubernetes
    - k3s
    - container
    - orchestration
    - cluster
    - devops

  issue_tracker_url: https://codeberg.org/kasefuchs/ansible-collection-general
  min_ansible_version: 2.2

dependencies:
  - role: kasefuchs.general.common
  - role: kasefuchs.general.download
