---
# Directory path where specific versions of AmneziaWG will be downloaded.
amneziawg_download_local_dir: "{{ (amneziawg_cache_local_dir, 'download') | ansible.builtin.path_join }}"

# Directory path where specific versions of AmneziaWG go will be downloaded.
amneziawg_download_go_local_dir: "{{ (amneziawg_download_local_dir, 'go') | ansible.builtin.path_join }}"

# Path to the AmneziaWG go for the current architecture.
amneziawg_download_go_local_file: "{{ (amneziawg_download_go_local_dir, 'current', ansible_facts.architecture) | ansible.builtin.path_join }}"

# Directory path where specific versions of AmneziaWG install tools will be downloaded.
amneziawg_download_tools_local_dir: "{{ (amneziawg_download_local_dir, 'tools') | ansible.builtin.path_join }}"

# Path to the AmneziaWG tools for the current architecture.
amneziawg_download_tools_local_file: "{{ (amneziawg_download_tools_local_dir, 'current', ansible_facts.architecture) | ansible.builtin.path_join }}"
