---
- name: Get latest Tailscale version
  when: tailscale_download_version == "latest"
  block:
    - name: Fetch latest Tailscale release on GitHub
      register: tailscale_download_github_release
      community.general.github_release:
        user: "{{ tailscale_download_github_user }}"
        repo: "{{ tailscale_download_github_repository }}"
        token: "{{ lookup('ansible.builtin.env', 'ANSIBLE_GITHUB_API_TOKEN') }}"
        action: latest_release

    - name: Set Tailscale version fact
      ansible.builtin.set_fact:
        tailscale_download_version: "{{ tailscale_download_github_release.tag | ansible.builtin.regex_replace('^v', '') }}"

- name: Download Tailscale archive
  ansible.builtin.include_role:
    name: kasefuchs.general.download
  vars:
    download_dir: "{{ tailscale_download_local_dir }}"
    download_url: "{{ tailscale_download_url }}"
    download_version: "{{ tailscale_download_version }}"
    download_architecture_map: "{{ tailscale_download_architecture_map }}"
