---
# Name of the currently used inventory.
common_inventory_name: "{{ inventory_dir | ansible.builtin.basename }}"

# Header of managed templates.
common_managed_header: "Managed by Ansible | Template: {{ template_path if not template_path.startswith('/') else (template_path | basename) }} (last modified: {{ template_mtime.strftime('%Y-%m-%d %H:%M:%S') }})"

# Local path for storing cache.
common_cache_local_dir: "{{ (playbook_dir, '../cache') | ansible.builtin.path_join }}"

# Local path for storing artifacts.
common_artifact_local_dir: "{{ (playbook_dir, '../artifacts', common_inventory_name) | ansible.builtin.path_join }}"

# List of unique system architectures among all hosts in the current play.
common_unique_architectures: "{{ ansible_play_hosts | map('ansible.builtin.extract', hostvars, 'ansible_architecture') | unique }}"
